PulleyLib/PulleyViewController.swift
The `PulleyPosition.all` shortcut was unavailable when Pulley is used as a framework, because the protection level used was the default, which is `internal`. Changing this to `public` makes it available outside of the framework so app view controllers can use it as shown in the example.
I also changed this to a let instead of a var, assuming there would be no reason to change what "all" means.
=> Fixed minor protection level issue

PulleyLib/PulleyViewController.swift
Hi,
first of all: Thanks for the library as it's helping us really well :)
While implementing it I noticed that some methods (which we need) were not called as expected and noted in Apple's Documentation. A view controller should always be notified when it was added to or removed from a container view controller.
This patch contains the required changes according to the docs. Specifically these two parts:
> If you are implementing your own container view controller, it must call the willMove(toParentViewController:) method of the child view controller before calling the removeFromParentViewController() method, passing in a parent value of nil.
> When your custom container calls the addChildViewController(_:) method, it automatically calls the willMove(toParentViewController:) method of …
=> Updated view controller containment calls according to Apple’s Documentation

PulleyLib/PulleyViewController.swift
I've run into an issue where setting the supportedDrawerPositions causes the setDrawerPosition to be called with animated=false during an animation. This would allow me to defer the setting of supportedDrawerPositions until the animation has completed. It seemed like the lest obtrusive way to fix the issue.
=> Add optional completion handlers for all animations that occur

PulleyLib/PulleyViewController.swift
This Pull Request adds a new property to `PulleyViewController` that returns the visible height of the drawer. This is handy for performing layout in the main content view controller that fits around the drawer.
=> Add visibleDrawerHeight property to PulleyViewController

PulleyLib/PulleyViewController.swift
This Pull Request adds the `allowsUserDrawerPositionChange` property to `PulleyViewController`, which essentially has the effect of disabling the `drawerScrollView`'s ability to scroll.
While we ideally want to allow the user to change the drawer's position at will, in some cases that isn't desirable. In our case, we're building a drag-and-drop interaction from the drawer to the main content view controller. While the drag is in progress, we collapse the drawer and turn it into an area the user can drop onto to cancel the drag. During this operation, we don't want the user to be able to manipulate the drawer.
=> Add allowsUserDrawerPositionChange property to PulleyViewController

Pulley.xcodeproj/project.pbxproj, Pulley/DrawerContentViewController.swift, Pulley/Main.storyboard, PulleyLib/PulleyViewController+Nested.swift, PulleyLib/PulleyViewController.swift
create class extension PulleyViewController+Nested
implement all delegate methods and pass delegate function to child drawerContentViewController
implement defaults for collapsedDrawerHeight and partialRevealDrawerHeight
A while ago, there was an issue on this project discussing nesting PulleyViewControllers. In the course of implementing Pulley in a project I've been working on, I have successfully achieved this. However, it quickly becomes problematic that, when nested in a second PulleyViewController, a custom view controller cannot implement PulleyDrawerViewControllerDelegate. This pull request resolves this by having PulleyViewController implement its own delegate, and passing functions to a compliant drawerContentViewController if available.
While fixing this, Swift complained about …
=> support nested PulleyViewControllers

Pulley.podspec
Similar to [this](https://github.com/seedco/StackViewController/commit/0d675de9466456c1eb5292cb140121656a02a024). You can't specify wildcard identifiers for file types in podspecs, it won't compile anymore.
Currently the files will not show up and throws warnings, this change fixes it works.
```
ld: warning: directory not found for option '-F/Users/mergesort/Library/Developer/Xcode/DerivedData/Picks-dnkbcqxucljrxufawsyycxtltfsh/Build/Products/Debug-iphonesimulator/Pulley'
ld: framework not found Pulley
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
=> Fixing podspec to work with new Xcode 9 build system

PulleyLib/PulleyViewController.swift, PulleyLib/UIView+constrainToParent.swift
This pull requests fixes the issues encountered in #110: Weird stuff happens in landscape on iPhone X.
Turns out there were a couple of different issue that compounded here. 
- The first issue is that the background dimming view didn't take into account that there might be left and right safe areas that it needs to fill - it'd only dim out the top. This (and the mask on its layer)has been updated to fill the entire screen so left and right safe areas are filled (red in this screenshot): 
- The second issue is that there's a bug that would cause the dimming progress to be set to `+Inf` if `partialRevealHeight == fullRevealHeight`, causing the dim to be pure black instead of the max of 0.5. This is now checked for.
- The third issue is that the "are we going towards fullscreen?" check when …
=> Fix issues with background dimming on iPhone X

PulleyLib/PulleyViewController.swift
On iPhone X's `landscapeRight` orientation the drawer uses the default safe areas even if the notch is on the other side of the screen. By splitting inset variable I can now set `panelInsetLeft` dynamically in `drawerDisplayModeDidChange` depending on the current device orientation and remove excess padding similar to Apple Maps.
=> Split panelInset variable into left and top components.

Pulley.podspec
as per 1.4.0 of cocoapods .swift_version files are deprecated: [http://blog.cocoapods.org/CocoaPods-1.4.0/](http://blog.cocoapods.org/CocoaPods-1.4.0/)
=> Add swift target

PulleyLib/PulleyViewController.swift
Before version 2.4.0 (commit 4131039), each `PulleyPosition` had a distinct `rawValue`. In that commit, `PulleyPosition` was changed from an enum to a class, and in the process, the `rawValue`s were changed, causing `partiallyRevealed` and `open` to both have the same `rawValue` of `1`.
This appears to be a mistake, because the `rawValue`s are used in several places to sort `PulleyPosition`s. This commit returns `open` and `closed` to their original `rawValue`s of `2` and `3`, respectively.
=> Remove duplicate PulleyPosition rawValue

PulleyLib/PulleyViewController.swift
Replace `notifyWhenInteractionEnds` callback which was deprecated in iOS 10 in favor of `notifyWhenInteractionChanges`.
=> Remove deprecated callback

PulleyLib/PulleyViewController.swift
If you notice in the demo app, initially the temperature controls aren't showing up because the  drawerChangedDistanceFromBottom delegate method would provide a distance of 0 and therefore the constraints would position the temperature controls incorrectly. This PR aims to fix that issue.
Addresses issue #230.
=> Fix a bug where the drawer distance delegate method would initially be the incorrect distance

Pulley.xcodeproj/project.pbxproj, Pulley/CustomMaskExample.swift, Pulley/DrawerContentViewController.swift, PulleyLib/PulleyViewController.swift
This pull request introduces non-API breaking support for custom drawer shapes supported through use of standard UIKit properties.
This may or may not be something which the maintainers wish to introduce into the main Pulley repo. Since we've managed to introduce this support in a non-intrusive, non-API breaking manner, I figured it worthwhile to submit a pull request.
Custom drawer shapes (i.e. for breakout elements) are currently unsupported by Pulley due to the manner in which the background UIEffectView and background dimming shadow are generated. Pulley currently only takes into account only rounded corners. An example of such a UI which is currently unsupported is shown below.
Pulley could allow for custom masks which ultimately support any simple contiguous shape for the drawers. …
=> Custom Masking

PulleyLib/PulleyViewController.swift
Closes: https://github.com/52inc/Pulley/issues/249
This is a `cornerPlacement` property which allows the developer to specify either `top` or `bottom` when `displayMode` == `.automatic` or `.leftSide`. 
@brendan09 do you have any ideas how the bottom corners can be unrounded when `.bottom` is specified? Basically want to mimic the corners for when `displayMode == .bottomDrawer` when in landscape mode.
=> Add cornerPlacement property

PulleyLib/PulleyViewController.swift
Outdated, see https://github.com/52inc/Pulley/pull/305#issuecomment-458943544
---
I needed to store the current drawer position to restore it on the next launch. Initially I implemented `Codable` for `PulleyPosition` but then realised that the code requires the position to be one of the predefined instances and not a custom one created be a `Decoder`.
Since there was already a method to get one of those instance from a given `String` I added another method to convert a given position to that `String`. Now you can store it (e.g. in `UserDefaults`) and safely restore the position on the next launch.
Example: 
```swift
extension UserDefaults {
var drawerPosition: PulleyPosition {
get {
guard let positionString = string(forKey: #function) else {
return .partiallyRevealed
}
return …
```
=> Make rawValue public

PulleyLib/PulleyViewController.swift
Instead of always setting the `drawerPosition` to `collapsed` when the mask is tapped, make it configurable.
=> Add option for pulley position when mask has been tapped.

PulleyLib/PulleyViewController.swift
I'm currently using Pulley for a project that contains a UISplitViewController, I found out that when I open a view controller that has Pulley in it, it does that bouncy effect. I tried to fix the issue and it worked for me, so I thought I should open a PR. :)
Here's a short video for the bug: https://youtu.be/h_ztzbAuBjw
Fixes: The bouncy drawer bug on iPad and Mac
Please describe the tests that you performed to verify your changes. Provide instructions so we can reproduce. Please provide details on how you tested supported versions of iOS and Xcode. Please make sure you have tested on all device size classes and orientations. Please also list any relevant details for your test configuration
**Test Configuration**
- Xcode Versions: 12.2
- Simulators:  iPad Pro 9.7 (14.2),
- Physical …
=> Fix the bouncy drawer bug on iPad and Mac

PulleyLib/PulleyViewController.swift
This uses the already existing `animationDuration` to animate when a primary or drawer view controller changes instead of hardcoding it to 0.5.
This alters the behavior, as the default `animationDuration` is set to `0.3`, but the hardcoded value was set to `0.5`. As this is only a cosmetic change, I would argue that it does not break previous behavior.
If you would like to introduce a new property for it instead of reusing the (then poorly named) `animationDuration`, I would be happy to get name suggestions.
=> Use animationDuration for transition animation duration

Pulley/Main.storyboard, PulleyLib/PulleyViewController.swift
This is a modification of [this](https://github.com/52inc/Pulley/pull/410) pull request to fix issue #409. That only removes the bounceOverflowMargin when the drawer is `.closed`.
Fixes #409
Please delete options that are not relevant.
Please describe the tests that you performed to verify your changes. Provide instructions so we can reproduce. Please provide details on how you tested supported versions of iOS and Xcode. Please make sure you have tested on all device size classes and orientations. Please also list any relevant details for your test configuration
**Test Configuration**
- Xcode Versions: [e.g. 12.x, 11.x, 10.x, 9.x]
- Simulators: [e.g. iPad Pro (14.x), iPhone SE (12.x)]
- Physical Hardware: [e.g. iPad Pro (14.x), iPhone SE (12.x)]
=> Fix hide bounce overflow on closed

PulleyLib/PulleyViewController.swift
This PR addresses an issue described [here](https://github.com/52inc/Pulley/issues/416).
There is a redundant subtraction from the frame of the drawerContentView with the bounceOverflowMargin var when it's displayed for .panel and .compact modes where bouncing is disabled.
Fixes # 416
Verified that the issue is fixed by inspecting the UI with XCode on iPad Simulator for panel and compact display modes. The change doesn't affect drawer mode so It's not tested in drawer mode. In the linked issue there is provided explanation on how to reproduce the issue this pull request fixes.
This code is probably a copy paste issue in the first place.
**Test Configuration**
- Xcode Versions: [12.5]
- Simulators: [iPad Pro (14.5)]
=> remove bounce overflow margin substract for panel

PulleyLib/PulleyPassthroughScrollView.swift, PulleyLib/PulleyViewController.swift
protocol `class` has been deprecated and replaced with `AnyObject`
Successful compilation with the following
**Test Configuration**
- Xcode Versions: [13.3 & 14.0]
=> Fix Xcode 14 compiler warning
